### PR TITLE
Allow customization

### PR DESCRIPTION
**Pull request by luxflux**
This changes allow a user to customize the name and footer of an application. There is an imprint page added to ensure licensing and attribution are still in place.

### CODE REVIEW

**Comment by luxflux** [comment]
Looks like Travis has a problem right now... Don't know how to fix the broken build... :/
screen shot 2015-08-14 at 13 10 02

**Comment by huerlisi** [comment]
Had to re-enable the project.

Thanks for this contribution. I'm fine with "re-branding" it as long as the AGPL conditions are fulfilled. And as I see by you're contributions you do follow the rules:-)

**Comment by huerlisi** [comment]
Build is broken, will fix it...

**Comment by huerlisi** [comment]
Fixed in #56

**Pull request merged**
