### PR TITLE
STI Addresses api

### PR DESCRIPTION
**Pull request by luxflux**
Support for companies along customers in the API.

### CODE REVIEW

**Comment by luxflux** [comment]
@huerlisi IMHO this is finished for the time being, do you mind reviewing it?

**Comment by huerlisi** [comment]
Looks good, will do a rebase merge because of the leap year issue.

**Comment by huerlisi** [comment]
Mmh, the merge issue does not come from the lear year commit as I expected, but is in the `app/api/bookyt/api/customers.rb` and `spec/api/bookyt/entities/person_spec.rb` files.

Could you please fix those as you know them better than I do;-)

Feel free to merge after fixing the conflicts.

Thanks!

**Comment by luxflux** [comment]
Fixed the merge conflicts and merged it. Thanks!

**Pull request merged**
