### PR TITLE
Cleanup and Update to Ruby 2.2 and Rails 4.2

### PR DESCRIPTION
**Pull request by kitsane**
First i will cleanout all unnecesary gems and stuff and then update. This is shurley completely opinionated, if you don't like you can add em back later.

Also, i only will look, that it runs only on postgres, i don't care about other dbs, cause i just don't care.

This branch will be broken for a while, so don't complain. When it's finished, it will need a lot of testing.

Regressions:

* [ ] ESR file upload is broken
* [ ] settings need to be migrated

### CODE REVIEW

**Comment by silvermind** [comment]
:+1:  very nice, I'll upgrade my installations if this is merged into master :) let me know if you need help. Would be great if there is a list, of broken features, if you clean the gems.

**Comment by kitsane** [comment]
Man, da i de Klinik händs ssh abgschalte, muess immer über https pushe und username und pw igäh. :rage:

**Comment by kitsane** [comment]
Is it possible, that authorization could be broken in some parts?

**Comment by huerlisi** [comment]
Reverted some gem upgrades and fixed a couple of regressions. Also did some more cleanup. Fixes for VESR and a settings migration is still pending.

To simplify development I intend to include the bookyt_* gems back into this code. In a later step I might also include the has_accounts* gems back into bookyt and build the gems out of this source.

**Pull request merged**
