### PR TITLE
Allow downloading a PDF via API

### PR DESCRIPTION
**Pull request by luxflux**
This PR allows you to download a PDF of a debit invoice via API.

### CODE REVIEW

**Comment by luxflux** [comment]
@huerlisi any news here? :smile:

**Comment by huerlisi** [comment]
Hi @luxflux 

I'm not sure if the API should return PDFs directly or just links to fetch them. I'll probably work on persisting PDFs on invoice creation/updating. This is implemented in another project of mine: https://github.com/CyTeam/hozr/blob/master/app/controllers/cases_controller.rb#L198

Anyhow, I'm not oposed to merge as is if you need it now;-)

I'll add you as a contributor, as you do good and valuable work. Please keep creating PRs, but feel free to merge yourself if there's no timely (1-2 days) reaction.

**Comment by huerlisi** [comment]
Added you as collaborator:-) Welcome on board :tada:

**Comment by luxflux** [comment]
> Added you as collaborator:-) Welcome on board :tada:

Thank you. I will handle this with care :smile: 

> I'm not sure if the API should return PDFs directly or just links to fetch them.
Hm, yeah. I thought about this as well, but we need access to the PDFs via API as we have to present them to users which don't have access to Bookyt.
Serving them via API from a database field would be fine for us as well, we just need this PDF :smile:

I'd merge it as it is for the time being. Persisting in the database is somehow a bigger topic as you also have to lock the invoice so that it doesn't get updated (which IMHO shouldn't be done anyway after it has been sent to the customer..). What do you think?

**Comment by huerlisi** [comment]
Yeah, go ahead with the merge.

**Pull request merged**
